version: '2'
services:
  mosquitto:
    image: toke/mosquitto
    container_name: homie-mqtt
    restart: always
    ports:
      - 1883:1883
      - 9001:9001 #eventually useful for websocket connections
    volumes:
      - ./etc/mosquitto:/mqtt/data
